// ==========================================================
// CASA DE ERVAS JUPIRA — Catálogo de Produtos
// Mais de 60 itens · 7 categorias
// ==========================================================

const CATALOGO = [
  // ==========================================================
  // 🌱 ERVAS (24 itens)
  // ==========================================================
  { id: 'arruda',       nome: 'Arruda',       categoria: 'ervas', energia: 'Proteção',       preco: 8.00,  validade: '12 meses', sku: 'ERV-001', badge: '🔥 Mais vendida', img: 'https://images.pexels.com/photos/1259491/pexels-photo-1259491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de descarrego poderoso. Remove energias pesadas e abre os caminhos espirituais.' },
  { id: 'guine',        nome: 'Guiné',        categoria: 'ervas', energia: 'Defesa',         preco: 7.00,  validade: '12 meses', sku: 'ERV-002', badge: null, img: 'https://images.pexels.com/photos/4705027/pexels-photo-4705027.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de proteção pesada. Ideal para limpeza profunda do campo energético.' },
  { id: 'alecrim',      nome: 'Alecrim',      categoria: 'ervas', energia: 'Purificação',    preco: 6.00,  validade: '14 meses', sku: 'ERV-003', badge: null, img: 'https://images.pexels.com/photos/11583514/pexels-photo-11583514.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de limpeza energética. Renova as energias e traz clareza mental.' },
  { id: 'manjericao',   nome: 'Manjericão',   categoria: 'ervas', energia: 'Prosperidade',   preco: 6.00,  validade: '10 meses', sku: 'ERV-004', badge: null, img: 'https://images.pexels.com/photos/33238933/pexels-photo-33238933.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de abertura de caminhos. Atrai fartura, sorte e prosperidade financeira.' },
  { id: 'alfazema',     nome: 'Alfazema',     categoria: 'ervas', energia: 'Paz',            preco: 9.00,  validade: '14 meses', sku: 'ERV-005', badge: null, img: 'https://images.pexels.com/photos/36256002/pexels-photo-36256002.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho relaxante para perfumar o ambiente e atrair harmonia espiritual.' },
  { id: 'rosa-branca',  nome: 'Rosa Branca',  categoria: 'ervas', energia: 'Amor próprio',   preco: 10.00, validade: '10 meses', sku: 'ERV-006', badge: null, img: 'https://images.pexels.com/photos/33227225/pexels-photo-33227225.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de autoestima e amor-próprio. Suaviza a energia do coração.' },
  { id: 'camomila',     nome: 'Camomila',     categoria: 'ervas', energia: 'Calma',          preco: 7.00,  validade: '12 meses', sku: 'ERV-007', badge: null, img: 'https://images.pexels.com/photos/33818568/pexels-photo-33818568.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho de equilíbrio emocional. Acalma a mente e traz serenidade.' },
  { id: 'espada-sj',    nome: 'Espada de S. Jorge', categoria: 'ervas', energia: 'Proteção máxima', preco: 9.00, validade: '12 meses', sku: 'ERV-008', badge: null, img: 'https://images.pexels.com/photos/13366118/pexels-photo-13366118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Poderosa erva de proteção contra inveja e mau-olhado. Banho de descarrego pesado.' },
  { id: 'comigo-np',    nome: 'Comigo Ninguém Pode', categoria: 'ervas', energia: 'Defesa contra inveja', preco: 8.00, validade: '12 meses', sku: 'ERV-009', badge: null, img: 'https://images.pexels.com/photos/37657373/pexels-photo-37657373.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Folha de proteção contra olho gordo e energias negativas do ambiente.' },
  { id: 'pimenteira',   nome: 'Pimenteira',   categoria: 'ervas', energia: 'Força e coragem',  preco: 7.00, validade: '10 meses', sku: 'ERV-010', badge: null, img: 'https://images.pexels.com/photos/35211392/pexels-photo-35211392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de fortalecimento espiritual. Dá coragem para enfrentar desafios.' },
  { id: 'erva-cidreira', nome: 'Erva Cidreira', categoria: 'ervas', energia: 'Tranquilidade', preco: 6.00, validade: '10 meses', sku: 'ERV-011', badge: null, img: 'https://images.pexels.com/photos/33227189/pexels-photo-33227189.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho calmante que acalma os nervos e equilibra as emoções.' },
  { id: 'hortela',      nome: 'Hortelã',      categoria: 'ervas', energia: 'Vitalidade',     preco: 6.00,  validade: '10 meses', sku: 'ERV-012', badge: null, img: 'https://images.pexels.com/photos/33694607/pexels-photo-33694607.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de renovação energética. Revigora o corpo e desperta a alegria.' },
  { id: 'louro',        nome: 'Louro',        categoria: 'ervas', energia: 'Vitória',        preco: 5.00,  validade: '14 meses', sku: 'ERV-013', badge: null, img: 'https://images.pexels.com/photos/9155665/pexels-photo-9155665.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Folha da vitória. Atrai sucesso, reconhecimento e conquistas profissionais.' },
  { id: 'canela',       nome: 'Canela',       categoria: 'ervas', energia: 'Prosperidade',   preco: 7.00,  validade: '16 meses', sku: 'ERV-014', badge: null, img: 'https://images.pexels.com/photos/33227173/pexels-photo-33227173.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de atrair dinheiro e fartura. Abre caminhos financeiros.' },
  { id: 'cravo-da-india', nome: 'Cravo da Índia', categoria: 'ervas', energia: 'Proteção e cura', preco: 8.00, validade: '18 meses', sku: 'ERV-015', badge: null, img: 'https://images.pexels.com/photos/33238919/pexels-photo-33238919.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Poderoso para defumações de proteção e atração de boas energias.' },
  { id: 'gengibre',     nome: 'Gengibre',     categoria: 'ervas', energia: 'Energia e ação', preco: 6.00,  validade: '14 meses', sku: 'ERV-016', badge: null, img: 'https://images.pexels.com/photos/3619240/pexels-photo-3619240.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de aquecer a energia. Dá impulso para realizar projetos e tomar decisões.' },
  { id: 'erva-doce',    nome: 'Erva Doce',    categoria: 'ervas', energia: 'Harmonia',       preco: 6.00,  validade: '12 meses', sku: 'ERV-017', badge: null, img: 'https://images.pexels.com/photos/8543600/pexels-photo-8543600.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Banho suave de harmonização. Atrai paz e doçura para as relações.' },
  { id: 'salvia',       nome: 'Sálvia',       categoria: 'ervas', energia: 'Purificação',    preco: 9.00,  validade: '14 meses', sku: 'ERV-018', badge: null, img: 'https://images.pexels.com/photos/33238932/pexels-photo-33238932.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva sagrada de purificação. Limpa ambientes e eleva a vibração espiritual.' },
  { id: 'patchouli',    nome: 'Patchouli',    categoria: 'ervas', energia: 'Aterramento',    preco: 10.00, validade: '18 meses', sku: 'ERV-019', badge: null, img: 'https://images.pexels.com/photos/32138214/pexels-photo-32138214.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de conexão com a terra. Acalma, centra e fortalece a estabilidade emocional.' },
  { id: 'jurema-preta', nome: 'Jurema Preta', categoria: 'ervas', energia: 'Força ancestral', preco: 12.00, validade: '14 meses', sku: 'ERV-020', badge: '🌟 Especial', img: 'https://images.pexels.com/photos/13366118/pexels-photo-13366118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva sagrada dos caboclos. Conexão profunda com a ancestralidade indígena.' },
  { id: 'aroeira',      nome: 'Aroeira',      categoria: 'ervas', energia: 'Cura física',    preco: 8.00,  validade: '14 meses', sku: 'ERV-021', badge: null, img: 'https://images.pexels.com/photos/33227225/pexels-photo-33227225.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva medicinal e espiritual. Usada em banhos de cura e fortalecimento do corpo.' },
  { id: 'barbatimao',   nome: 'Barbatimão',   categoria: 'ervas', energia: 'Cicatrização',   preco: 7.00,  validade: '14 meses', sku: 'ERV-022', badge: null, img: 'https://images.pexels.com/photos/37098340/pexels-photo-37098340.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de cura espiritual. Ajuda a cicatrizar feridas da alma.' },
  { id: 'sucupira',     nome: 'Sucupira',     categoria: 'ervas', energia: 'Proteção',       preco: 9.00,  validade: '16 meses', sku: 'ERV-023', badge: null, img: 'https://images.pexels.com/photos/33227189/pexels-photo-33227189.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva de proteção energética poderosa. Usada em defumações e banhos de descarrego.' },
  { id: 'angelica',     nome: 'Angélica',     categoria: 'ervas', energia: 'Purificação',    preco: 10.00, validade: '14 meses', sku: 'ERV-024', badge: null, img: 'https://images.pexels.com/photos/33818568/pexels-photo-33818568.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400', desc: 'Erva dos anjos. Purificação profunda e conexão com planos superiores.' },

  // ==========================================================
  // 🕯️ DEFUMAÇÃO (14 itens)
  // ==========================================================
  { id: 'def-guardiao',     nome: 'Defumação Guardião',     categoria: 'defumacao', energia: 'Proteção máxima',  preco: 15.00, validade: '24 meses', sku: 'DEF-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Guiné + Sal grosso. Poderosa defumação para proteção do lar.' },
  { id: 'def-cabocla',      nome: 'Defumação Cabocla',      categoria: 'defumacao', energia: 'Harmonia do lar',  preco: 18.00, validade: '24 meses', sku: 'DEF-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Alfazema + Camomila + Rosas. Defumação especial para paz no lar.' },
  { id: 'def-abertura',     nome: 'Defumação Abertura',     categoria: 'defumacao', energia: 'Prosperidade',     preco: 18.00, validade: '24 meses', sku: 'DEF-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Alecrim + Canela + Louro. Abre caminhos e atrai boas energias.' },
  { id: 'def-jupira',       nome: 'Defumação Jupira ✨',    categoria: 'defumacao', energia: 'Descarrego + Cura', preco: 22.00, validade: '24 meses', sku: 'DEF-004', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Alecrim + Folhas de Jurema. Defumação especial da Cabocla Jupira.' },
  { id: 'def-protecao-p',   nome: 'Defumação Proteção Pesada', categoria: 'defumacao', energia: 'Defesa total', preco: 20.00, validade: '24 meses', sku: 'DEF-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Espada de S. Jorge + Guiné + Arruda + Sal. Proteção máxima para ambientes.' },
  { id: 'def-limpeza',      nome: 'Defumação Limpeza Profunda', categoria: 'defumacao', energia: 'Limpeza', preco: 16.00, validade: '24 meses', sku: 'DEF-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Ervas amargas + cascas cítricas. Limpeza energética pesada do ambiente.' },
  { id: 'def-prosperidade', nome: 'Defumação Prosperidade',  categoria: 'defumacao', energia: 'Fartura',         preco: 18.00, validade: '24 meses', sku: 'DEF-007', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Canela + Cravo + Louro + Gengibre. Defumação para atrair dinheiro e fartura.' },
  { id: 'def-amor',         nome: 'Defumação Amor',          categoria: 'defumacao', energia: 'Atração',         preco: 18.00, validade: '24 meses', sku: 'DEF-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Rosa + Alfazema + Canela. Doce defumação para atrair amor e romance.' },
  { id: 'def-paz',          nome: 'Defumação Paz',           categoria: 'defumacao', energia: 'Serenidade',      preco: 15.00, validade: '24 meses', sku: 'DEF-009', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Camomila + Erva Doce + Hortelã. Acalma ambientes e traz tranquilidade.' },
  { id: 'def-descarrego',   nome: 'Defumação Descarrego',    categoria: 'defumacao', energia: 'Descarrego',      preco: 17.00, validade: '24 meses', sku: 'DEF-010', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Guiné + Alecrim + Pimenta. Descarrego poderoso para pessoas e ambientes.' },
  { id: 'def-sete-ervas',   nome: 'Defumação Sete Ervas',    categoria: 'defumacao', energia: 'Completa',        preco: 22.00, validade: '24 meses', sku: 'DEF-011', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Sete ervas sagradas em uma única defumação. Para limpeza e equilíbrio completos.' },
  { id: 'def-sao-miguel',   nome: 'Defumação São Miguel',    categoria: 'defumacao', energia: 'Proteção divina', preco: 20.00, validade: '24 meses', sku: 'DEF-012', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Ervas de proteção + incenso de mirra. Para proteção espiritual pesada.' },
  { id: 'def-sete-flechas', nome: 'Defumação Sete Flechas',  categoria: 'defumacao', energia: 'Cura + Defesa',   preco: 22.00, validade: '24 meses', sku: 'DEF-013', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Jurema + Arruda + Alecrim + Guiné. Linha especial dos caboclos flecheiros.' },
  { id: 'def-jurema',       nome: 'Defumação Jurema',        categoria: 'defumacao', energia: 'Linha dos Caboclos', preco: 25.00, validade: '24 meses', sku: 'DEF-014', badge: '🌟 Especial', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Folhas de Jurema + Ervas da mata. Defumação ancestral de conexão com a Jurema.' },

  // ==========================================================
  // 🕯️ VELAS (12 itens)
  // ==========================================================
  { id: 'vela-guardia',    nome: 'Vela Guardiã',        categoria: 'velas', energia: 'Proteção',        preco: 22.00, validade: '36 meses', sku: 'VEL-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Alecrim. Vela artesanal para proteção do lar e da família.' },
  { id: 'vela-cabocla',    nome: 'Vela Cabocla',         categoria: 'velas', energia: 'Tranquilidade',   preco: 25.00, validade: '36 meses', sku: 'VEL-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Lavanda + Camomila. Vela suave para equilíbrio e harmonia.' },
  { id: 'vela-jupira',     nome: 'Vela Jupira ✨',       categoria: 'velas', energia: 'Cura espiritual',  preco: 28.00, validade: '36 meses', sku: 'VEL-003', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Jurema + Alfazema. Vela especial da Linha Jupira para cura espiritual.' },
  { id: 'vela-atrai',      nome: 'Vela Atrai',           categoria: 'velas', energia: 'Prosperidade',    preco: 25.00, validade: '36 meses', sku: 'VEL-004', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Canela + Laranja. Vela para atrair prosperidade e boas oportunidades.' },
  { id: 'vela-arruda',     nome: 'Vela Erva Poderosa',   categoria: 'velas', energia: 'Descarrego',      preco: 24.00, validade: '36 meses', sku: 'VEL-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Sal grosso. Vela poderosa para descarrego e limpeza.' },
  { id: 'vela-guine',      nome: 'Vela Defesa',          categoria: 'velas', energia: 'Defesa',          preco: 24.00, validade: '36 meses', sku: 'VEL-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Guiné + Alecrim. Vela de proteção pesada para ambientes.' },
  { id: 'vela-alfazema',   nome: 'Vela Paz & Calma',     categoria: 'velas', energia: 'Serenidade',      preco: 22.00, validade: '36 meses', sku: 'VEL-007', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Alfazema + Camomila. Vela suave para noites tranquilas e meditação.' },
  { id: 'vela-sete-dias',  nome: 'Vela Sete Dias',       categoria: 'velas', energia: 'Trabalho contínuo', preco: 35.00, validade: '36 meses', sku: 'VEL-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Vela de 7 dias com ervas. Para trabalhos espirituais prolongados.' },
  { id: 'vela-jeje',       nome: 'Vela Jejê',            categoria: 'velas', energia: 'Força dos ancestrais', preco: 30.00, validade: '36 meses', sku: 'VEL-009', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Vela especial com ervas da linha Jejê. Tradição e força ancestral.' },
  { id: 'vela-coco',       nome: 'Vela de Coco',         categoria: 'velas', energia: 'Purificação',      preco: 20.00, validade: '36 meses', sku: 'VEL-010', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Vela natural de coco com ervas. Purificação suave e conexão com a natureza.' },
  { id: 'vela-rosa',       nome: 'Vela Rosa Mística',    categoria: 'velas', energia: 'Amor próprio',     preco: 26.00, validade: '36 meses', sku: 'VEL-011', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Pétalas de rosa + alfazema. Vela para atrair amor-próprio e autoestima.' },
  { id: 'vela-canela',     nome: 'Vela Canela Quente',   categoria: 'velas', energia: 'Atração',          preco: 24.00, validade: '36 meses', sku: 'VEL-012', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Canela + Cravo. Vela aromática para aquecer relações e atrair paixão.' },

  // ==========================================================
  // 🎁 KITS (12 itens)
  // ==========================================================
  { id: 'kit-banho',           nome: 'Kit Banho (3 ervas)',        categoria: 'kits', energia: 'Personalizado',   preco: 18.00, validade: '12 meses', sku: 'KIT-001', badge: 'Econômico', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Escolha 3 ervas do nosso catálogo. Kit personalizado para sua necessidade.' },
  { id: 'kit-jupira',          nome: 'Kit Jupira 🌟',              categoria: 'kits', energia: 'Cura + Proteção',  preco: 62.00, validade: '24 meses', sku: 'KIT-002', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Kit completo: Ervas + Vela Jupira + Defumação Jupira + Guia de uso.' },
  { id: 'kit-bem-estar',       nome: 'Kit Bem-Estar Cabocla',      categoria: 'kits', energia: 'Equilíbrio',      preco: 35.00, validade: '12 meses', sku: 'KIT-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Alfazema + Camomila + Vela Cabocla. Para dias que pedem calma e acolhimento.' },
  { id: 'kit-defumacao',       nome: 'Kit Defumação Completo',     categoria: 'kits', energia: 'Proteção total',  preco: 55.00, validade: '24 meses', sku: 'KIT-004', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: '3 defumações + incensário de barro + guia de defumação.' },
  { id: 'kit-protecao',        nome: 'Kit Proteção Pesada',        categoria: 'kits', energia: 'Defesa máxima',   preco: 48.00, validade: '12 meses', sku: 'KIT-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Guiné + Espada de S. Jorge + Vela Guardiã. Proteção completa.' },
  { id: 'kit-prosperidade',    nome: 'Kit Prosperidade',           categoria: 'kits', energia: 'Fartura',         preco: 42.00, validade: '12 meses', sku: 'KIT-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Manjericão + Louro + Canela + Vela Atrai. Para atrair dinheiro e fartura.' },
  { id: 'kit-amor-proprio',    nome: 'Kit Amor Próprio',           categoria: 'kits', energia: 'Autoestima',      preco: 38.00, validade: '12 meses', sku: 'KIT-007', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Rosa Branca + Alfazema + Vela Rosa Mística. Para cuidar de si mesma(o).' },
  { id: 'kit-descarrego',      nome: 'Kit Descarrego',             categoria: 'kits', energia: 'Limpeza',         preco: 45.00, validade: '12 meses', sku: 'KIT-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Arruda + Guiné + Alecrim + Defumação Descarrego. Limpeza energética completa.' },
  { id: 'kit-meditacao',       nome: 'Kit Meditação & Paz',        categoria: 'kits', energia: 'Paz interior',    preco: 40.00, validade: '12 meses', sku: 'KIT-009', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Camomila + Alfazema + Incenso Sândalo + Vela Cabocla.' },
  { id: 'kit-iniciacao',       nome: 'Kit Iniciação Espiritual',   categoria: 'kits', energia: 'Jornada',         preco: 68.00, validade: '24 meses', sku: 'KIT-010', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: '7 ervas + Defumação Sete Ervas + Vela + Incensário + Guia completo.' },
  { id: 'kit-jurema',          nome: 'Kit Jurema & Caboclos',      categoria: 'kits', energia: 'Ancestralidade',  preco: 72.00, validade: '24 meses', sku: 'KIT-011', badge: '🌟 Especial', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Jurema + Defumação Cabocla + Vela Jupira + Guia dos Caboclos.' },
  { id: 'kit-banho-7',         nome: 'Kit Banho Completo (7 ervas)', categoria: 'kits', energia: 'Transformação', preco: 32.00, validade: '12 meses', sku: 'KIT-012', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: '7 ervas selecionadas para um banho completo de limpeza e renovação.' },

  // ==========================================================
  // 🔥 INCENSOS (8 itens)
  // ==========================================================
  { id: 'inc-arruda',     nome: 'Incenso Arruda',        categoria: 'incensos', energia: 'Proteção',      preco: 10.00, validade: '36 meses', sku: 'INC-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incenso natural de Arruda. Para limpeza e proteção do ambiente.' },
  { id: 'inc-alecrim',    nome: 'Incenso Alecrim',       categoria: 'incensos', energia: 'Purificação',   preco: 10.00, validade: '36 meses', sku: 'INC-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incenso natural de Alecrim. Purifica e renova as energias do ambiente.' },
  { id: 'inc-alfazema',   nome: 'Incenso Alfazema',      categoria: 'incensos', energia: 'Paz',           preco: 10.00, validade: '36 meses', sku: 'INC-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incenso suave de Alfazema. Perfuma e acalma o ambiente.' },
  { id: 'inc-sandalo',    nome: 'Incenso Sândalo',       categoria: 'incensos', energia: 'Meditação',     preco: 12.00, validade: '36 meses', sku: 'INC-004', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incenso sagrado de Sândalo. Eleva a vibração para meditação e conexão.' },
  { id: 'inc-mirra',      nome: 'Incenso Mirra',         categoria: 'incensos', energia: 'Elevação',       preco: 14.00, validade: '36 meses', sku: 'INC-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Resina de Mirra. Incenso poderoso para elevação espiritual e proteção.' },
  { id: 'inc-benjoim',    nome: 'Incenso Benjoim',       categoria: 'incensos', energia: 'Purificação',   preco: 12.00, validade: '36 meses', sku: 'INC-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Resina de Benjoim. Purificação profunda e limpeza energética do ambiente.' },
  { id: 'inc-jupira',     nome: 'Incenso Jupira ✨',     categoria: 'incensos', energia: 'Força cabocla',  preco: 15.00, validade: '36 meses', sku: 'INC-007', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Blend especial com ervas da mata. Incenso da Linha Jupira.' },
  { id: 'inc-cravo',      nome: 'Incenso Cravo',         categoria: 'incensos', energia: 'Energia',        preco: 10.00, validade: '36 meses', sku: 'INC-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incenso de Cravo da Índia. Ativa a energia do ambiente e afasta vibrações densas.' },

  // ==========================================================
  // 🚿 BANHOS PRONTOS (8 itens)
  // ==========================================================
  { id: 'banho-descarrego',   nome: 'Banho de Descarrego',       categoria: 'banhos', energia: 'Limpeza',       preco: 14.00, validade: '8 meses', sku: 'BAN-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de arruda + guiné + alecrim. Para descarregar energias negativas.' },
  { id: 'banho-protecao',    nome: 'Banho de Proteção',          categoria: 'banhos', energia: 'Defesa',         preco: 14.00, validade: '8 meses', sku: 'BAN-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de espada de S. Jorge + guiné + sal grosso.' },
  { id: 'banho-prosperidade', nome: 'Banho de Prosperidade',     categoria: 'banhos', energia: 'Fartura',        preco: 15.00, validade: '8 meses', sku: 'BAN-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de manjericão + canela + louro. Para atrair dinheiro e fartura.' },
  { id: 'banho-amor-proprio', nome: 'Banho de Amor Próprio',     categoria: 'banhos', energia: 'Autoestima',     preco: 15.00, validade: '8 meses', sku: 'BAN-004', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de rosa branca + alfazema. Para elevar a autoestima.' },
  { id: 'banho-paz',         nome: 'Banho de Paz',               categoria: 'banhos', energia: 'Serenidade',     preco: 13.00, validade: '8 meses', sku: 'BAN-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de camomila + alfazema + erva doce. Acalma o coração e a mente.' },
  { id: 'banho-jupira',      nome: 'Banho Jupira ✨',            categoria: 'banhos', energia: 'Cura + Força',   preco: 18.00, validade: '8 meses', sku: 'BAN-006', badge: 'Linha Jupira', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho especial da Cabocla Jupira. Cura espiritual e fortalecimento.' },
  { id: 'banho-abertura',    nome: 'Banho de Abertura',          categoria: 'banhos', energia: 'Novos caminhos', preco: 14.00, validade: '8 meses', sku: 'BAN-007', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de alecrim + canela + gengibre. Abre caminhos e atrai oportunidades.' },
  { id: 'banho-vitoria',     nome: 'Banho da Vitória',           categoria: 'banhos', energia: 'Triunfo',        preco: 15.00, validade: '8 meses', sku: 'BAN-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Banho pronto de louro + alecrim + canela. Para vencer desafios e conquistar metas.' },

  // ==========================================================
  // 🎍 OFERENDAS (6 itens)
  // ==========================================================
  { id: 'of-vela-mel',     nome: 'Vela de Mel',          categoria: 'oferendas', energia: 'Doçura',        preco: 12.00, validade: '36 meses', sku: 'OFE-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Vela natural de mel para oferendas. Agrada entidades e traz doçura espiritual.' },
  { id: 'of-frutas-secas',  nome: 'Frutas Secas (100g)', categoria: 'oferendas', energia: 'Oferenda',       preco: 10.00, validade: '6 meses', sku: 'OFE-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Mix de frutas secas para oferendas nas matas. Para caboclos e entidades da natureza.' },
  { id: 'of-milho',         nome: 'Milho de Pipoca (200g)', categoria: 'oferendas', energia: 'Fartura',    preco: 8.00,  validade: '12 meses', sku: 'OFE-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Milho especial para oferendas. Tradicional para caboclos e entidades da linha de Oxóssi.' },
  { id: 'of-batata',        nome: 'Batata Doce (500g)',  categoria: 'oferendas', energia: 'Sustento',       preco: 7.00,  validade: '1 mês', sku: 'OFE-004', badge: 'Fresco', img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Batata doce fresca para oferendas. Alimento tradicional das entidades caboclas.' },
  { id: 'of-velas-7',       nome: 'Kit 7 Velas Oferenda', categoria: 'oferendas', energia: 'Devoção',      preco: 18.00, validade: '36 meses', sku: 'OFE-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: '7 velas brancas para oferendas e trabalhos espirituais.' },
  { id: 'of-farinha',       nome: 'Farinha de Mandioca (500g)', categoria: 'oferendas', energia: 'Tradição', preco: 8.00, validade: '8 meses', sku: 'OFE-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Farinha de mandioca torrada. Tradicional em oferendas para caboclos e entidades da mata.' },

  // ==========================================================
  // 🪶 ACESSÓRIOS (8 itens)
  // ==========================================================
  { id: 'acess-incensario',   nome: 'Incensário de Barro',      categoria: 'acessorios', energia: 'Utilitário',    preco: 22.00, validade: 'Ilimitada', sku: 'ACE-001', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Incensário artesanal de barro. Ideal para defumações e incensos.' },
  { id: 'acess-pena',        nome: 'Pena de Gavião',           categoria: 'acessorios', energia: 'Conexão',        preco: 8.00,  validade: 'Ilimitada', sku: 'ACE-002', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Pena natural de gavião. Usada em defumações e rituais de limpeza.' },
  { id: 'acess-penacho',     nome: 'Penacho Mini',             categoria: 'acessorios', energia: 'Força cabocla',  preco: 15.00, validade: 'Ilimitada', sku: 'ACE-003', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Mini penacho artesanal com penas coloridas. Para altares e rituais.' },
  { id: 'acess-guia',        nome: 'Guia de Contas (Caboclo)', categoria: 'acessorios', energia: 'Proteção',       preco: 25.00, validade: 'Ilimitada', sku: 'ACE-004', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Guia de contas com cores da Cabocla Jupira. Amarelo, verde e vermelho.' },
  { id: 'acess-sino',        nome: 'Sino Ritual',              categoria: 'acessorios', energia: 'Chamado',         preco: 18.00, validade: 'Ilimitada', sku: 'ACE-005', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Sino artesanal para abertura de trabalhos espirituais. Som limpo e vibrante.' },
  { id: 'acess-tigela',      nome: 'Tigela de Barro',          categoria: 'acessorios', energia: 'Utilitário',    preco: 20.00, validade: 'Ilimitada', sku: 'ACE-006', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Tigela artesanal de barro. Para oferendas e preparo de banhos.' },
  { id: 'acess-velas-cores', nome: 'Kit Velas Coloridas (5un)', categoria: 'acessorios', energia: 'Variada',       preco: 15.00, validade: '36 meses', sku: 'ACE-007', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: '5 velas coloridas (amarela, verde, vermelha, azul, branca). Para seus rituais.' },
  { id: 'acess-defumador',   nome: 'Defumador de Metal',       categoria: 'acessorios', energia: 'Praticidade',    preco: 28.00, validade: 'Ilimitada', sku: 'ACE-008', badge: null, img: 'https://images.unsplash.com/photo-1593001874117-c99c80fbe6d4?auto=format&fit=crop&w=400&q=80', desc: 'Defumador de metal com cabo. Prático e seguro para defumações diárias.' },
];

// ==========================================================
// Helpers
// ==========================================================
function formatPreco(valor) {
  return `R$ ${valor.toFixed(2).replace('.', ',')}`;
}

function getProduto(id) {
  return CATALOGO.find(p => p.id === id);
}

function getPorCategoria(cat) {
  if (!cat || cat === 'todos') return CATALOGO;
  return CATALOGO.filter(p => p.categoria === cat);
}

function getCategorias() {
  return [...new Set(CATALOGO.map(p => p.categoria))];
}

// Stats
function totalProdutos() { return CATALOGO.length; }
function totalCategorias() { return getCategorias().length; }
function precoMinimo() { return Math.min(...CATALOGO.map(p => p.preco)); }
function precoMaximo() { return Math.max(...CATALOGO.map(p => p.preco)); }
